### ISSUE TITLE
Helicopter in distress event

### ISSUE THREAD

**Issue by BetterDeadThanZed** [BetterDeadThanZed/serverissues#2]
The helicopter/plane in distress event - the aircraft crashes right after spawning on Takistan, unconfirmed on Napf.

**Comment by ekroemer** [comment]
While I have seen very short spawn-crash intervals occasionally, at least on Napf normally all works as intended. I've even seen a MV22 pass my position 4 times in 5min before it crashed.
I guess the choppers do really fly before they crash and so, when they spawn in front of a mountain, their life expectancy will be very low, indeed :

**Comment by BetterDeadThanZed** [comment]
I've lowered the fly speed from 250 to 150 and increased the fly height from 150m to 250m. We'll see if this makes a difference.
